inputs_def:
  - handle: file
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: file
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: File to path
icon: ":fa6-solid:file-invoice:"
