inputs_def:
  - handle: folder
    description: Input
    json_schema:
      type: string
      ui:widget: dir
outputs_def:
  - handle: folder
    description: Output
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Empty folder
icon: ":carbon:folder-off:"
description: Delete all contents in the folder
