executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
inputs_def:
  - handle: binary
    json_schema:
      contentMediaType: oomol/bin
outputs_def:
  - handle: file_path
    json_schema:
      type: string
      minLength: 1
      ui:widget: file
title: Write temp file
icon: ":fa6-solid:file-import:"
