inputs_def:
  - handle: folder
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: only_file_name
    json_schema:
      type: boolean
    value: false
outputs_def:
  - handle: files
    description: Output
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
  - handle: folder_exists
    json_schema:
      type: boolean
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Read folder
icon: ":fa6-solid:folder-open:"
