inputs_def:
  - handle: dir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: sort
    json_schema:
      type: boolean
    value:
    nullable: true
outputs_def:
  - handle: path_array
    description: Output
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Dir to path list
icon: ":fa6-solid:folder-tree:"
