inputs_def:
  - handle: file
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: binary
    description: Output
    json_schema:
      contentMediaType: oomol/bin
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: File to binary
icon: ":fa6-solid:file-export:"
