inputs_def:
  - handle: url
    description: ""
    json_schema:
      type: string
  - handle: file_dir
    description: Specify the folder path where the file will be saved. If it does
      not exist, specify a specific path.
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
  - group: Options
    collapsed: false
  - handle: query
    json_schema:
      type: object
      additionalProperties:
        type: string
    value:
      {}
    nullable: false
  - handle: headers
    json_schema:
      type: object
      additionalProperties:
        type: string
    value:
      {}
    nullable: false
  - handle: timeout
    json_schema:
      type: integer
      minimum: 0
    value: 0
    nullable: false
  - handle: retry_times
    json_schema:
      type: integer
      minimum: 1
    value: 1
    nullable: false
  - handle: reset_filename
    description: Whether to rename the downloaded file name. If false, the file name
      in the URL will be retained.
    json_schema:
      type: boolean
    value: true
    nullable: false
outputs_def:
  - handle: file_path
    description: Final saved
    json_schema:
      type: string
      ui:widget: save
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: "URL to file "
icon: ":carbon:cloud-download:"
description: Initiate an HTTP request to download the content of the URL and
  save it to a file.
private: false
