inputs_def:
  - handle: url
    description: Input
    json_schema:
      type: string
outputs_def:
  - handle: file
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: "URL to file "
icon: ":fa6-solid:cloud-arrow-down:"
