inputs_def:
  - handle: source_file
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: destination_folder
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: destination_file
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 490.7877197265625
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Copy file
icon: ":carbon:document-multiple-01:"
