inputs_def:
  - handle: dir
    description: Input
    json_schema:
      type: string
      ui:widget: dir
outputs_def:
  - handle: dir
    description: Output
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Empty dir
icon: ":fa6-solid:trash-can:"
