inputs_def:
  - handle: folder
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: sort
    json_schema:
      type: boolean
    nullable: false
    value: false
  - handle: traverse
    json_schema:
      type: boolean
    value: false
  - handle: absolute_path
    json_schema:
      type: boolean
    value: true
outputs_def:
  - handle: file_paths
    description: Output
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
  - handle: folder_exists
    json_schema:
      type: boolean
    nullable: false
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: List files from folder
icon: ":fa6-solid:folder-tree:"
