executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: true
inputs_def:
  - handle: binary
    json_schema:
      contentMediaType: oomol/bin
  - handle: suffix
    json_schema:
      type: string
    value:
    nullable: true
  - handle: file_path
    json_schema:
      type: string
      ui:widget: save
    value:
    nullable: true
outputs_def:
  - handle: file_path
    json_schema:
      type: string
      ui:widget: save
title: Binary save as file
icon: ":carbon:transform-binary:"
