executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: true
inputs_def:
  - handle: binary
    json_schema:
      contentMediaType: oomol/bin
  - handle: suffix
    json_schema:
      type: string
    nullable: true
    value:
  - handle: file_path
    json_schema:
      type: string
      ui:widget: file
    nullable: true
    value:
outputs_def:
  - handle: file_path
    json_schema:
      type: string
      minLength: 1
      ui:widget: file
title: Binary save as file
icon: ":fa6-solid:floppy-disk:"
