inputs_def:
  - handle: binary
    description: Input
    json_schema:
      contentMediaType: oomol/bin
  - handle: file_name
    description: The converted file name
    json_schema:
      type: string
  - handle: output_folder
    description: The converted file save folder path
    json_schema:
      type: string
      ui:widget: dir
  - group: Options
    collapsed: true
  - handle: mkdir
    description: Whether to create the folder if it does not exist
    json_schema:
      type: boolean
    value: false
  - handle: when_file_exists
    description: What to do when a file already exists at the save path?
    json_schema:
      enum:
        - override
        - ignore
        - rename
        - error
      ui:options:
        labels:
          - Override
          - Ignore
          - Rename
          - Error
    value: error
outputs_def:
  - handle: file_path
    json_schema:
      type: string
      ui:widget: save
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: Binary to file
icon: ":carbon:transform-binary:"
