inputs_def:
  - handle: url
    description: Initiate an HTTP request to download the contents of the URL and
      return it in binary format
    json_schema:
      type: string
  - group: Options
    collapsed: true
  - handle: query
    json_schema:
      type: object
      additionalProperties:
        type: string
    value:
      {}
    nullable: false
  - handle: headers
    json_schema:
      type: object
      additionalProperties:
        type: string
    value:
      {}
    nullable: false
  - handle: timeout
    json_schema:
      type: integer
      minimum: 0
    value: 0
    nullable: false
  - handle: retry_times
    json_schema:
      type: integer
      minimum: 1
    value: 1
    nullable: false
outputs_def:
  - handle: binary
    description: ""
    json_schema:
      contentMediaType: oomol/bin
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: URL to binary
icon: ":carbon:cloud-data-ops:"
