inputs_def:
  - handle: source_folder
    description: Input
    json_schema:
      type: string
      ui:widget: dir
  - handle: destination_folder
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: destination_folder
    description: Output
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Copy folder
icon: ":fa6-solid:copyright:"
