inputs_def:
  - handle: source_files
    description: ""
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
  - handle: destination_folder
    json_schema:
      type: string
      ui:widget: dir
    nullable: true
outputs_def:
  - handle: destination_files
    description: ""
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
ui:
  default_width: 499.2611083984375
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Copy flies
icon: ":carbon:document-multiple-02:"
