inputs_def:
  - handle: source_files
    description: Input
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
  - handle: destination_folder
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: destination_folder
    description: Output
    json_schema:
      type: string
      ui:widget: dir
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Copy flies
icon: ":carbon:copy-file:"
